### ISSUE TITLE
 '' expected a map, got 'ptr'

### ISSUE THREAD

**Issue by Yancy0220** [spf13/viper#1709] opened 2023-12-11 09:44 UTC
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.8.1

### Go Version

1.21.5

### Config Source

Manual set

### Format

TOML

### Code reproducing the issue

```go
if err = v.Unmarshal(&c); err != nil {
		return nil, err
	}
	return c, nil
```

### Expected Behavior

报错：  '' expected a map, got 'ptr'

### Actual Behavior

报错：  '' expected a map, got 'ptr'

**Comment by juliusbachnick** [comment] 2023-12-11 09:55
I'm relatively sure that this is a duplicate of #1706

**Comment by sagikazarmark** [comment] 2023-12-15 12:32
It is. Please follow that issue.

**Closed by sagikazarmark** 2023-12-15 12:32 UTC
Labels: kind/bug
