### ISSUE TITLE
The key named y or n will be replaced with true or false after reading.

### ISSUE THREAD

**Issue by chaijingchao1982** [spf13/viper#1286] opened 2022-01-19 09:59 UTC
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.

### Viper Version

1.10.1

### Go Version

1.17.1

### Config Source

Files

### Format

YAML

### Code reproducing the issue

```go
test:
  a: "aaa"
  b: "bbb"
  y: "yyy"
  n: "nnn"
```

### Expected Behavior

The read data is : map[test:map[a:aaa b:bbb n:nnn y:yyy]]

### Actual Behavior

The read data is : map[test:map[a:aaa b:bbb false:nnn true:yyy]]

### Steps To Reproduce

Use Viper to read the yaml I defined.

**Comment by sagikazarmark** [comment] 2022-01-19 10:16
Duplicate of #1146
Duplicate of #960

https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md#unquoted-y-and-n-characters-get-replaced-with-true-and-false-when-reading-a-yaml-file

**Closed** 2022-01-19 10:16 UTC
Labels: resolution/duplicate
