### ISSUE TITLE
cannot find package hcl/hcl/printer

### ISSUE THREAD

**Issue by ionutnechita** [spf13/viper#1086] opened 2021-02-24 13:34 UTC
go/src/github.com/spf13/viper/viper.go:40:2: cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
        /usr/lib/go-1.15/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
        /nfs/ka/home/ionutnex/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)

**Comment by sagikazarmark** [comment] 2021-02-24 13:36
Duplicate of #1083

**Closed by sagikazarmark** 2021-02-24 13:36 UTC
Labels: kind/bug

**Comment by kevinsingapore** [comment] 2021-02-26 10:08
1 and i had met the same error，u need to use hcl_v1.0.0；
2 my env go_v1.15；
3 hashicorp/hcl v1.0.0 url:
```shell
https://github.com/hashicorp/hcl/releases/tag/v1.0.0
```

**Comment by VladG1986** [comment] 2021-06-23 03:10
Any update guys?
