### ISSUE TITLE
Read config file only if one exists

### ISSUE THREAD

**Issue by lucperkins** [spf13/viper#718] opened 2019-06-15 15:25 UTC
I have a use case where it'd be beneficial for me to read a config file *only if one exists*, allowing for non-mandatory config files (and thus fallback to flags, environment variables, and defaults for config).

Here's an example:

```go
viper.SetConfigFile("config.yaml")

err := viper.ReadInConfigIfExists()
```

This allows for an "opt-in" approach to using configuration files.

**Comment by sagikazarmark** [comment] 2019-06-17 09:45
This is a duplicate of #1 

The [proposed solution](https://github.com/spf13/viper/issues/1#issuecomment-451533395) is checking the returned error.

Does that work for you?

**Comment by lucperkins** [comment] 2019-06-17 15:19
@sagikazarmark That does work and I appreciate the pointer. I do, however, strongly prefer the solution in #719. I totally get the argument that it's important to keep the surface area of the API small. But I also think that there are two different intentions and approaches behind `ReadInConfig` and `ReadInConfigIfExists`.

I'd be curious what others think.

**Comment by lucperkins** [comment] 2019-06-22 18:35
Addresed in #719

**Closed** 2019-06-22 18:35 UTC
