### ISSUE TITLE
Default values doesn't work (SetDefault function)

### ISSUE THREAD

**Issue by vlkv** [spf13/viper#158] opened 2016-02-05 17:32 UTC
Hi! I'm trying to use default values for my configuration params. They seem to be NOT working. Here is the example:
```
package main
import (
	"fmt"
	"github.com/spf13/viper"
)

func main() {
	c := viper.New()
	c.SetConfigFile("./config.json")
	c.SetConfigType("json")
	err := c.ReadInConfig()
	if err != nil {
		fmt.Errorf("Error %v\n", err)
	}

	//c.SetTypeByDefaultValue(false)
	c.SetDefault("params.p2", "TWO")
	c.SetDefault("params.p3", "333")

	fmt.Println(c.Get("params.p1"))
	fmt.Println(c.Get("params.p2"))
	fmt.Println(c.Get("params.p3"))
	fmt.Println(c.Get("params.p4"))

	/* Output:
	one   - correct
	two   - correct
	<nil> - WRONG! Expected 333
	<nil> - correct
	*/
}
```

And the config.json is
```
{
	"params": {
		"p1": "one",
		"p2": "two"
	}
}
```

**Comment by vlkv** [comment] 2016-02-05 17:33
If I'm doing something wrong, please correct my example. Thanks in advance

**Comment by kofalt** [comment] 2016-02-08 22:24
I think this is a duplicate of #71. A workaround can be found in that ticket: https://github.com/spf13/viper/issues/71#issuecomment-112797593.

**Comment by vlkv** [comment] 2016-02-09 04:52
Thanks for response, but after changing the line 
```
c.SetDefault("params.p3", "333")
```
with
```
if c.Get("params.p3") == nil {
    		c.SetDefault("params.p3", "333")
	}
```
It still doesn't work. The output is the same

**Comment by jgsqware** [comment] 2016-03-31 07:31
@vlkv Do you find a way to make it work finally?

**Comment by vlkv** [comment] 2016-04-01 07:21
c.Set("params.p3", "333") <<<<< I'd like to do this BEFORE load actual values from file. If I would do this AFTER - then defaults lose their sense, becase I would do this every time in every place after load.

So, I've created my own config module https://github.com/vlkv/ya-go-config It's not as powerfull as viper, it's tiny little simple. But I don't need more.

**Comment by jgsqware** [comment] 2016-04-01 11:18
@vlkv I'm reading the conf file before the `c.Get()`

If `Get == nil`means that the parameter was not in the file. So it set a value.

It's behaviour of default value isn't it?

**Comment by vlkv** [comment] 2016-04-01 12:14
https://github.com/spf13/viper/issues/158#issue-131703922 Here is what I've expected

**Comment by awishformore** [comment] 2016-10-08 08:05
Fixed by PR #195

**Closed by awishformore** 2016-10-08 08:05 UTC

**Comment by davidmusau** [comment] 2022-07-10 08:50
func getEnvValue(key string, defaultValue string) string {
	value := viper.GetString(key)
	if value != "" {
		return value
	}
	return defaultValue
}

**Comment by Zanda256** [comment] 2024-02-27 17:50
> func getEnvValue(key string, defaultValue string) string {
> value := viper.GetString(key)
> if value != "" {
> return value
> }
> return defaultValue
> }

This surely works.
