### ISSUE TITLE
the key in 'n', 'y' convert to bool

### ISSUE THREAD

**Issue by yyeiei** [spf13/viper#930] opened 2020-06-28 11:22 UTC
hello, i'm using viper to get config from a .yaml file, i have following yaml:
```
Bloomfilter:
  Name: example
  N: 1000000
  P: 0.001
```
and the struct:
```
type bloomfilter struct {
	Name string  `yaml:"Name"`
	N    uint64  `yaml:"Y"`
	P    float64 `yaml:"P"`
}
```
after unmarshal, i can get all the correct values except N (N is always 0), it looks that would be convert to bool when the key is 'n' or 'y', then bloomfilter.N = 0 as zerovalue?
i am not sure this is a bug or ... feature? so i can not use ‘n’ or 'y' as the key?

**Comment by sagikazarmark** [comment] 2022-01-01 18:52
Duplicate of #1146

tl;dr quote the keys

**Closed by sagikazarmark** 2022-01-01 18:52 UTC
Labels: resolution/duplicate
