### ISSUE TITLE
Config file boilerplates .dist files

### ISSUE THREAD

**Issue by lopezator** [spf13/viper#511] opened 2018-06-07 08:02 UTC
I come from PHP/Symfony world. 

In there, we had a config.yml.dist file where you write your config file "spec", with all the required parameters and structure with dummy values.

Every time you execute Composer by bash, it checks your config.yml file (ignored in gitignore) and: 

1.- Ask you by bash prompt all the missing config key/values, using as default value (if you just hit enter it would use that) the value provided in the config.yml.dist.
2.- Create/update config.yml

I don't know if this even has sense in golang or in cobra/viper. How do you work with dev/prod? 

Thoughts?

**Comment by mamyn0va** [comment] 2018-10-12 06:20
It's a (partial) duplicate of https://github.com/spf13/viper/issues/215.

**Closed** 2018-10-23 13:28 UTC
