### ISSUE TITLE
Viper ignores toml tags

### ISSUE THREAD

**Issue by okoshovetc** [spf13/viper#954] opened 2020-08-17 18:26 UTC
Seems to be a duplicate of https://github.com/spf13/viper/issues/544, but here I provide simple standalone reproducer

#### Go version

```bash
$ go version
go version go1.14.7 linux/amd64
```

#### Go ENV
```bash
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/okoshovets/.cache/go-build"
GOENV="/home/okoshovets/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="gitlab.corp.mail.ru/*"
GONOSUMDB="gitlab.corp.mail.ru/*"
GOOS="linux"
GOPATH="/home/okoshovets/.go"
GOPRIVATE="gitlab.corp.mail.ru/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build169159720=/tmp/go-build -gno-record-gcc-switches"
```

#### Reproducer
```go
package main

import (
	"fmt"
	"os"

	"github.com/BurntSushi/toml"
	"github.com/spf13/viper"
)

type Config struct {
	Section Section
}

type Section struct {
	A int `toml:"section_a"`
}

var inValidConfigFile = "invalid_config.toml"
var inValidConfig = `
[section]
a=1
section_a=2
`

func writeTOML() error {
	f1, err := os.Create(inValidConfigFile)
	if err != nil {
		return err
	}

	_, err = f1.Write([]byte(inValidConfig))
	if err != nil {
		return err
	}

	return nil
}

func main() {
	err := writeTOML()
	if err != nil {
		panic(err.Error())
	}

	viper.SetConfigType("toml")
	viper.SetConfigFile(inValidConfigFile)

	var configViper Config
	var configBurntSushi Config

	if _, err := toml.DecodeFile(inValidConfigFile, &configBurntSushi); err != nil {
		panic(err.Error())
	}

	if err := viper.ReadInConfig(); err != nil {
		panic(err.Error())
	}
	if err := viper.Unmarshal(&configViper); err != nil {
		panic(err.Error())
	}

	if configBurntSushi.Section.A != configViper.Section.A {
		fmt.Printf("%s config.Section.A Viper=%d BurntSushi=%d\n", inValidConfigFile, configViper.Section.A, configBurntSushi.Section.A)
		os.Exit(1)
	}

	fmt.Println("Everything OK")
	os.Exit(0)
}
```

#### Output
```
invalid_config.toml config.Section.A Viper=1 BurntSushi=2
exit status 1
```

#### Expected output
```
Everything OK
```

**Comment by sagikazarmark** [comment] 2020-08-17 21:42
I don't think the two are related.

Viper doesn't use toml tags for unmarshaling, you need to use mapstructure.

See details in the documentation: https://github.com/spf13/viper#unmarshaling

**Comment by sagikazarmark** [comment] 2020-08-17 21:42
Closing as it is working as intended.

**Closed by sagikazarmark** 2020-08-17 21:42 UTC
Labels: resolution/invalid
