### ISSUE TITLE
Does not support golang composite?

### ISSUE THREAD

**Issue by ezhishui** [spf13/viper#822] opened 2020-01-08 08:43 UTC
yml:
```yml
a1: 1
b1: 2
```

```go
type A struct{
	A1 string
}
type B struct {
	A
	B1 string
}

obj := B{}
vip.Unmarshal(&obj);
```
Viper can not set A1=1?

**Comment by sagikazarmark** [comment] 2020-01-08 09:48
Duplicate of #797 #820

**Closed by sagikazarmark** 2020-01-08 09:48 UTC
