### ISSUE TITLE
for keep clean , remove provider ( remote ) to new repo  

### ISSUE THREAD

**Issue by mlboy** [spf13/viper#974] opened 2020-09-11 03:34 UTC
for keep clean , remove provider ( remote ) to new repo , such as: spf13/viper-remote-etcd .

**Comment by sagikazarmark** [comment] 2020-09-12 16:36
Duplicate of #887

We can't do that for Viper 1, we plan to do it in Viper 2.

**Closed by sagikazarmark** 2020-09-12 16:36 UTC
