### ISSUE TITLE
Viper 引用包错误 github.com/hashicorp/hcl/hcl/printer

### ISSUE THREAD

**Issue by smallk1002** [spf13/viper#1234] opened 2021-09-28 09:22 UTC
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.

### Viper Version

master

### Go Version

1.14.4 

### Config Source

Defaults

### Format

Other (specify below)

### Repl.it link

https://github.com/spf13/viper/blob/master/internal/encoding/hcl/codec.go

### Code reproducing the issue

```go
import (
  "github.com/hashicorp/hcl/hcl/printer"
)


../github.com/spf13/viper/internal/encoding/hcl/codec.go:8:2: cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
```

### Expected Behavior

It should be quoted successfully

### Actual Behavior

It should be quoted successfully

### Steps To Reproduce

This third-party package can no longer be used

**Comment by sagikazarmark** [comment] 2021-09-28 09:33
Duplicate of #1083

**Closed by sagikazarmark** 2021-09-28 09:33 UTC
Labels: kind/bug
