### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by monolighter** [spf13/viper#1077] opened 2021-02-12 06:07 UTC
$ go get github.com/spf13/viper
package github.com/hashicorp/hcl/hcl/printer: cannot find package "github.com/hashicorp/hcl/hcl/printer"

**Comment by Quantum12k** [comment] 2021-02-12 07:00
same problem

**Comment by sagikazarmark** [comment] 2021-02-12 08:26
@monolighter @Quantum12k do you have Go modules enabled? Viper requires go modules, otherwise it doesn't work.

**Comment by sagikazarmark** [comment] 2021-02-12 09:34
Duplicate of #1076

**Closed by sagikazarmark** 2021-02-12 09:34 UTC
Labels: kind/bug
