### ISSUE TITLE
Consul ACL token support

### ISSUE THREAD

**Issue by sabir012** [spf13/viper#903] opened 2020-05-04 10:03 UTC
Hi Team,
I am using Viper with Consul as a remote provider. After enabling ACL in Consul, Viper stopped working as there is no possibility to inject token to Viper. Is there any way to set up Viper that can connect to ACL enabled Consul?

**Comment by sagikazarmark** [comment] 2020-05-04 10:07
Duplicate of #841

**Closed by sagikazarmark** 2020-05-04 10:07 UTC
