### ISSUE TITLE
Stripping underscores makes viper unable to find env vars

### ISSUE THREAD

**Issue by dionb** [spf13/viper#1009] opened 2020-10-26 12:13 UTC
Am I going mad, or is there definitely a problem when stripping the _ from env names? I want to make it so that you can configure my app with either env, config file, or flags. And then use viper.Unmarshal() to write the values into my config object. But stripping the underscores from env keys makes viper miss them completely. 
In the following test I would expect to get either ":9090" or ":9091" (which is not important at the moment) but no value is found at all. It would appear that the key replacer is being run before the prefix is being stripped and checked, and so it can no longer be found and the keys are rejected. 

```

func NewViper() *viper.Viper {
	v := viper.New()
	v.AutomaticEnv()
	return v
}

func SetEnv(t *testing.T, key string, value string) {
	err := os.Setenv(key, value)
	require.NoError(t, err)
}

func TestStripUnderscore(t *testing.T) {
	viper := NewViper()
	viper.SetEnvPrefix("rp")
	viper.SetEnvKeyReplacer(strings.NewReplacer("_", ""))
	SetEnv(t, "RP_LISTENSOCKET", ":9090")
	SetEnv(t, "RP_LISTEN_SOCKET", ":9091")
	defer os.Clearenv()
	assert.Equal(t, ":9090", viper.Get("listensocket"))
}

func TestStripUnderscoreWithoutPrefix(t *testing.T) {
	viper := NewViper()
	viper.SetEnvKeyReplacer(strings.NewReplacer("_", ""))
	SetEnv(t, "LISTEN_SOCKET", ":9091")
	defer os.Clearenv()
	assert.Equal(t, ":9091", viper.Get("listensocket"))
}

```

**Comment by dionb** [comment] 2020-10-26 12:16
Here's the relevant source from my app. It seems to be working perferctly aside from the env variables not being found if the string replacer is present (and I have checked/updated env var names appropriately).
```

type config struct {
	ValidDomains  []string `mapstructure:"validdomains"`
	ValidRegions  []string `mapstructure:"validregions"`
	DefaultRegion string   `mapstructure:"defaultregion"`
	ListenSocket  string   `mapstructure:"listensocket"`
}

func loadConfig() config {
	viper.AutomaticEnv()
	viper.SetEnvPrefix("rp")
	viper.SetEnvKeyReplacer(strings.NewReplacer("_", ""))

	viper.ReadInConfig()

	pflag.StringSlice("validRegions", nil, "The list of regions that we currently support")
	pflag.String("defaultRegion", "SGP", "The region to use if none is specified in the request")
	pflag.String("listenSocket", ":80", "The socket/interface:port that this proxy should listen on")
	pflag.StringSlice("validDomains", nil, "The set of string that should have the region appended when found in the host in a request")

	pflag.Parse()
	err := viper.BindPFlags(pflag.CommandLine)
	if err != nil {
		log.Fatal(err)
	}

	conf := config{}
	err = viper.Unmarshal(&conf)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("%#v\n", conf)

	return conf
}
```

**Comment by sagikazarmark** [comment] 2020-10-26 14:13
Automatic env doesn't work with unmarshal on its own. You either have to bind the env var manually, or set a default using `SetDefault`.

Duplicate of #761

**Closed by sagikazarmark** 2020-10-26 14:13 UTC
