### ISSUE TITLE
Accessing nested keys does not work

### ISSUE THREAD

**Issue by Telmo** [spf13/viper#67] opened 2015-05-08 11:45 UTC
Accessing nested keys doesn't seem to work as is described in the documentation:

using 

```
                {
                        "ImportPath": "github.com/spf13/viper",
                        "Rev": "29f1858f8782bd55fa432c459f7e64b7032b3c33"
                },
```
 Go version is:

`go version go1.4.2 darwin/amd64`

This is the test

```
package main

import (
	"fmt"
	"log"

	"github.com/spf13/viper"
)

func main() {
	viper.SetConfigName("test")
	err := viper.ReadInConfig()
	if err != nil {
		log.Println(err)
	}
	fmt.Println("Keys:", viper.AllKeys())
	fmt.Println("AllSettings:", viper.AllSettings())
	log.Println(viper.GetString("datastore.metric.host"))
}
```

This is the JSON file being used as config, is a copy and paste form the documentation.
```
{
	"host": {
		"address": "localhost",
		"port": 5799
	},
	"datastore": {
		"metric": {
			"host": "127.0.0.1",
			"port": 3099
		},
		"warehouse": {
			"host": "198.0.0.1",
			"port": 2112
		}
	}
}
```

This is the result:

```
 rmoral00@HQSML-312266 ❯ godep go build && ./test
Keys: [host datastore]
AllSettings: map[host:map[address:localhost port:5799] datastore:map[metric:map[host:127.0.0.1 port:3099] warehouse:map[host:198.0.0.1 port:2112]]]
2015/05/08 07:43:34
```

**Comment by kzvezdarov** [comment] 2015-05-08 14:58
Cannot reproduce. Check if the revision that you are using is up to date with the tip of `master` (`godep` might have frozen you at a certain point before the nested key changes). This is the output of the test for me:
```
Keys: [host datastore]
AllSettings: map[host:map[address:localhost port:5799] datastore:map[metric:map[host:127.0.0.1 port:3099] warehouse:map[host:198.0.0.1 port:2112]]]
2015/05/08 10:56:21 127.0.0.1
```

**Comment by kzvezdarov** [comment] 2015-05-08 15:03
@Telmo Found the issue, you are way behind the most recent version. This is the commit that you are using:
https://github.com/spf13/viper/commit/29f1858f8782bd55fa432c459f7e64b7032b3c33
Which is from December 04. Nested key access was introduced later. Updating your version should fix the issue. Closing this

**Closed by kzvezdarov** 2015-05-08 15:03 UTC
