### ISSUE TITLE
Feature Request: Case Sensitive Keys

### ISSUE THREAD

**Issue by aaronbuchwald** [spf13/viper#1013] opened 2020-11-03 03:13 UTC
Case sensitive keys are useful in many contexts, but they are not currently possible using viper.

**Comment by aaronbuchwald** [comment] 2020-11-03 05:46
Actually, even in the case where I call Get on an individual key which maps to a JSON object, it still makes the keys of that JSON object lower case as well.

```
{"key": {"CaseSensitive": {"key":"value"}}}
```

Is there any way to get the value of the "CaseSensitive" key in this example using viper?

**Comment by yongjiapro** [comment] 2020-11-03 12:25
See [https://github.com/spf13/viper/pull/635/commits/2cb5cbf43cc6d8b777a6f1baae164e3853c8430d](https://github.com/spf13/viper/pull/635/commits/2cb5cbf43cc6d8b777a6f1baae164e3853c8430d)

**Comment by sagikazarmark** [comment] 2020-11-03 13:35
Duplicate of #1014

**Closed by sagikazarmark** 2020-11-03 13:35 UTC

**Comment by dreamlu** [comment] 2022-12-13 02:29
https://github.com/spf13/viper/commit/2cb5cbf43cc6d8b777a6f1baae164e3853c8430d
why delete it? it's useful
